### ISSUE TITLE
Where to enter OpenAI API key

### ISSUE THREAD

**Issue by KennyDenvers** [ichichikin/obsidian-plugin-interactivity#1]
Hi! 
Looks like a fascinating and very handy plugin! 
Where can I enter my OpenAI key? Could not find any hint in the plugin settings. (desktop or iPhone)

**Comment by KennyDenvers** [comment]
Ok, I guess I found where to enter the OpenAI API key (under "Advanced Options"). Still I cannot figure out how to get a response from ChatGPT.
When I use "@@hello" or any other prompt, I am not getting a response and often Obsidian shows at the bottom of the screen "Interactivity is busy ⌛".
Math calculations only seem to work for me when I deactivate "Advanced Options".

**Comment by KennyDenvers** [comment]
Also getting:
When I am trying to insert an Excel table with @excel_table(path) --> "NameError: name 'excel_table' is not defined"

**Comment by ichichikin** [comment]
Hi @KennyDenvers,

I'm glad you liked the plugin! It looks like you need to align some settings.
1. Please check if have all python modules in the `py_modules` directory, so the path would look like this: `./your_vault/.obsidian/plugins/interactivity/py_modules/*.py`.
2. Assuming that you have set up Python and have all the necessary Python files in the `py_modules` directory and `py_manager.py` in the plugin’s root directory, you need to configure the `Shell CLI Arguments` setting with the value specified on the GitHub page:
```
-iq
##plugin##py_manager.py
```
3. In order to set up the OpenAI API-key, please follow [this instruction](https://github.com/ichichikin/obsidian-plugin-interactivity?tab=readme-ov-file#commands-to-run-after-starting-the-shell).
4. Remember that the `Advanced Options` cannot be activated on your mobile Obsidian due to some system limitations. But, you can set up the plugin to call ChatGPT API [with pure JavaScript](https://github.com/ichichikin/obsidian-plugin-interactivity?tab=readme-ov-file#javascript-andvanced-shortcuts).

Let me know if that helped.

**Comment by KennyDenvers** [comment]
Hi @ichichikin,

thank you for your e-mail and your remarks about aligning my settings!

* 
I have tried to observe what you described - and have copied the matplotlib, pandas, openai, tabulate folders (!) into the py_modules directory (as I could not find their " matplotlib.py ( http://matplotlib.py/ ) " files etc.)  (with the exception of the openai.py ( http://openai.py/ ) file). Is that the way to go?

* Another question: What is py_manager.py ( http://py_manager.py/ ) and where can I find it?

I think these are the points that I am currently still struggling with. I appreciate it if you could give me some more support with these topics.

Cheers,

Kenny

***

Kai Dombrowski
Drakestr. 21h
12205 Berlin
(030) 784 70 87
(0152) 3191 2295

**Comment by ichichikin** [comment]
I hope all has been resolved.

**Comment by KennyDenvers** [comment]
Thank you @ichichikin for your hints about aligning my settings!
Obviously I am a newbie when it comes to Python and integrating its modules into Obsidian. 😅

1. 
I have tried to observe what you described - and have copied the matplotlib, pandas, openai, tabulate folders (!) into the py_modules directory (as I could not find their "[matplotlib.py](http://matplotlib.py/)" files etc.)  (with the exception of the [openai.py](http://openai.py/) file). Is that the way to go?
![image](https://github.com/ichichikin/obsidian-plugin-interactivity/assets/90445513/c7cad15a-a882-4670-b72f-833521127e9d)

2.
Another question: What is py_manager.py and where can I find it?

I think these are the points that I am currently still struggling with. I appreciate it if you could give me some more guidance as to the direction in which I could move ahead with these topics.

**Comment by ichichikin** [comment]
Don't worry, I'll try to help you to handle all that.

**1. Make sure you have installed Python**

Check if Python 3 is already installed:
Open a terminal (Command Prompt on Windows, Terminal on macOS/Linux).
Type `python3 --version` and press Enter.
If Python 3 is installed, you will see the version number. If Python 3 is not installed, download and install it from [python.org](https://www.python.org/downloads/).

**2. Install the required libraries**

Use your terminal to install the libraries:
```bash
pip3 install matplotlib openai pandas tabulate
```
You don't need to copy any of these libraries to the plugin's directory.

**3. Make sure you have the latest version of the plugin installed properly**

The actual version is 0.0.4. With this one you should be able to locate the `py_manager.py` file in the plugin’s root directory, which looks like `./your_vault/.obsidian/plugins/interactivity/`.

**4. Follow the steps from my previous reply**

[This one](https://github.com/ichichikin/obsidian-plugin-interactivity/issues/1#issuecomment-2144207176).

**Comment by KennyDenvers** [comment]
Thanks @ichichikin for your continuing support! 
I confirmed that I had Python 3 installed and tried installing the modules but was confirmed that everything was installed already. 
My issue now is with the py_manager.py file which is not available in the plugin's root directory (or anywhere on my harddrive for that matter). I had uninstalled and reinstalled the plugin without any success where py_manager.py is concerned. The files in the plugin's root folder that are visible there are: main.js, manifest.json and styles.css - nothing else. :-)

**Comment by ichichikin** [comment]
@KennyDenvers, I got it now. I will update the README.md to make that clearer.
So, you can get all the necessary files directly from the [GitHub project](https://github.com/ichichikin/obsidian-plugin-interactivity/archive/refs/heads/main.zip), copy the `py_manager.py` file and the `py_modules` directory into the Interactivity plugin's root directory.
Remember that Python won't run on your mobile devices. You can set up some complex [JavaScript commands](https://github.com/ichichikin/obsidian-plugin-interactivity?tab=readme-ov-file#javascript-advanced-shortcuts) instead.

**Comment by KennyDenvers** [comment]
@ichichikin - thanks! 😅
I copied the files into the plugin's root directory. Now "plot" and "excel_table" work (excel table is apparently missing the first "|" symbol(s)).
The "@@What's the average hourly wage?" (to stick to that example) does not work, however. (I have inserted my OpenAI API key.) In this case nothing happens (the cursor, just in that line becomes unreactive, and I see "Interactivity is busy" in the task bar. I've tried changing the "text shortcut for running commands" but that did not help eiter (also I don't understand how that should work with the single "@" for excel_table and plot and the (double) "@@" for OpenAI chat). It would be great if you could clarify that for me as well.

![image](https://github.com/ichichikin/obsidian-plugin-interactivity/assets/90445513/677b66a3-58f4-46f5-b5ed-2f31610502d7)

**Comment by KennyDenvers** [comment]
Hi @ichichikin !
I read the readme and included the "@@" syntax in the "Text Shortcuts for Running Commands". With "@@" or "@chat" I am getting the following error message:

![image](https://github.com/ichichikin/obsidian-plugin-interactivity/assets/90445513/6144fb44-46c6-4a0f-86f5-bd25ad70ee8c)

**Comment by ichichikin** [comment]
Hi, @KennyDenvers 
Apparently, OpenAI updated their API, so that error occurred. I made some changes to the `py_modules/chat.py` module. Please, replace it with the newer one from this repository.

**Comment by KennyDenvers** [comment]
Works! Great! Thank you!

***

Kai Dombrowski
Drakestr. 21h
12205 Berlin
(030) 784 70 87
(0152) 3191 2295
